// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
// ...
await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6CbJFoc-8Gi12TdnabrlX-TF6XutKg-4',
    appId: '1:257988195168:web:e32e62854b9a57b25c2405',
    messagingSenderId: '257988195168',
    projectId: 'voting-app-183e7',
    authDomain: 'voting-app-183e7.firebaseapp.com',
    storageBucket: 'voting-app-183e7.appspot.com',
    measurementId: 'G-D4WWYHPERL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa_pSH6hwFjVJHPLAjNFsikZpliesL6Uo',
    appId: '1:257988195168:android:2219663e76f391285c2405',
    messagingSenderId: '257988195168',
    projectId: 'voting-app-183e7',
    storageBucket: 'voting-app-183e7.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJbtqUR96S8wIwCR52HdpD37jYsPsSl5Q',
    appId: '1:257988195168:ios:8d047bba1310b3285c2405',
    messagingSenderId: '257988195168',
    projectId: 'voting-app-183e7',
    storageBucket: 'voting-app-183e7.appspot.com',
    iosBundleId: 'com.example.votingApp.RunnerTests',
  );
}
